### ISSUE TITLE
Doesn't work with scoped modules

### ISSUE THREAD

**Issue by zeg-io** [siddharthkp/auto-install#34] opened 2016-08-24 18:12 UTC
`var log = require('@zetta/log-colors');` doesn't work. the error reference lists only the scope and not the scoped module

```
⠋ Installing @zetta
npm ERR! addLocal Could not install /Users/tonyarcher/code/zetta/sql-boilerplate/@zetta
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@zetta" "--save"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! path /Users/tonyarcher/code/zetta/sql-boilerplate/@zetta
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/tonyarcher/code/zetta/sql-boilerplate/@zetta'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/tonyarcher/code/zetta/sql-boilerplate/@zetta'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tonyarcher/code/zetta/sql-boilerplate/npm-debug.log

⚠ @zetta installation failed
```

**Comment by siddharthkp** [comment] 2016-08-24 18:24
Duplicate of https://github.com/siddharthkp/auto-install/issues/11 ?

**Comment by zeg-io** [comment] 2016-08-24 19:21
No, not a dupe of 11.

I decided that rather than freeloading I'd fix it.  Please merge the below pull request

https://github.com/siddharthkp/auto-install/pull/35

**Closed as completed** 2016-08-25 18:32 UTC
Labels: bug
